# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f524dce64074453a0155c52882f3c804"
name = "upsell-cart-drawer"
handle = "upsell-cart-drawer-9"
application_url = "https://challenge-honduras-qt-hansen.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-new-shopping.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://challenge-honduras-qt-hansen.trycloudflare.com/auth/callback",
  "https://challenge-honduras-qt-hansen.trycloudflare.com/auth/shopify/callback",
  "https://challenge-honduras-qt-hansen.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[app_proxy]
url = "https://challenge-honduras-qt-hansen.trycloudflare.com"
subpath = "savemetafield-api"
prefix = "a"

[pos]
embedded = false
